# Generated by Django 4.2.14 on 2024-07-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttablemodel',
            name='answer_text',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Текстовое поле ответа'),
        ),
        migrations.AlterField(
            model_name='categoryquestionmodel',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Проводится сейчас'),
        ),
    ]
