# Generated by Django 4.2.14 on 2024-07-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_alter_resulttablemodel_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.IntegerField(verbose_name='Порядковый номер')),
                ('category_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_app.categoryquestionmodel')),
            ],
            options={
                'verbose_name': 'группа ответа',
                'verbose_name_plural': 'группы ответов',
            },
        ),
    ]
