# Generated by Django 4.2.14 on 2024-07-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_groupresultsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttablemodel',
            name='group_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_app.groupresultsmodel', verbose_name='Группа ответа'),
        ),
    ]
